language: ruby
rvm:
  - 2.3
  
cache: bundler

env:
  - RAILS_ENV=test

services:
  - mysql
  
install:
  - bundle install
  
before_script:
  - cp .travis.database.yml config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:setup
  - RAILS_ENV=test bundle exec rake db:migrate
